FROM public.ecr.aws/lambda/python:3.9

WORKDIR /var/task

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src/create_task /var/task/

ARG ENVIRONMENT=local
COPY .env /var/task/.env

CMD ["app.lambda_handler"]