FROM public.ecr.aws/lambda/python:3.9

WORKDIR /var/task

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src/get_tasks /var/task/
COPY .env /var/task/.env

CMD ["app.lambda_handler"]