FROM public.ecr.aws/lambda/python:3.9

WORKDIR /var/task

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src/delete_task /var/task/

# Copy .env file for local development (this will be ignored in production)
COPY .env /var/task/.env

CMD ["app.lambda_handler"]